### ISSUE TITLE
Special values conflict

### ISSUE THREAD

**Issue by b-s-a** [Zeda/z80float#22]
```
$ ./single.py -inf +inf 3.4028236e+38 3.4028235e+38 3.4028237e+38 NaN
.db $FF,$FF,$FF,$00  ;-inf /* Ooops!!! */
.db $FF,$FF,$7F,$00  ;+inf /* Ooops!!! */
.db $00,$00,$00,$00  ;3.4028236e+38 /* Ooops!!! */
.db $FF,$FF,$7F,$FF  ;3.4028235e+38
.db $FF,$FF,$7F,$00  ;3.4028237e+38 /* Ooops!!! */
Traceback (most recent call last):
  File "./single.py", line 59, in <module>
    print(dbify(tofloat(i))+"  ;"+i)
  File "./single.py", line 37, in tofloat
    a=int(x)
ValueError: cannot convert float NaN to integer
```

From manual:
> The mantissa requires the top three bits to contain specific values:
>
```
    +0 is represented as 0x00
    -0 is represented as 0x80
    +inf is represented as 0x40
    -inf is represented as 0xC0
    NaN is represented as 0x20
```

**Comment by Zeda** [comment]
Okay, thank you! I have fixed it, and there was an issue with `extended.py` converting `NaN`, `+inf`, and `-inf` that I fixed as well :)

**Comment by b-s-a** [comment]
It is not all. Inf and max.positive number are converted incorrectly by single.py.

**Comment by Zeda** [comment]
Okay, sorry about that, I had just woken up and didn't read the issue entirely. Here is the output:
```
.db $FF,$FF,$C0,$00  ;-inf
.db $FF,$FF,$40,$00  ;+inf
.db $00,$00,$40,$00  ;3.4028236e+38
.db $FF,$FF,$7F,$FF  ;3.4028235e+38
.db $FF,$FF,$40,$00  ;3.4028237e+38
.db $00,$00,$20,$00  ;NaN
```

I'm going to reopen this in case you find more bugs, thanks again!

**Comment by Zeda** [comment]
It has been a couple of weeks since the fix, so I'm going to go ahead and close this. If there are any issues, feel free to re-open it.
